site_name: opensourceleg
repo_url: https://github.com/neurobionics/opensourceleg
site_url: https://neurobionics.github.io/opensourceleg
site_description: An open-source software library for numerical computation, data acquisition, and control of lower-limb robotic prostheses.
site_author: Open-Source Leg
edit_uri: edit/main/docs/
repo_name: neurobionics/opensourceleg
copyright: Maintained by <a href="https://github.com/senthurayyappan">Senthur Ayyappan</a>.

nav:
  - Overview: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/neurobionics/opensourceleg
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/opensourceleg

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
